# Generated by Django 3.1.1 on 2022-05-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eDiary.signup'),
        ),
    ]
