# Generated by Django 3.1.1 on 2022-05-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0002_auto_20220526_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eDiary.signup'),
        ),
    ]
